In [1]:
import numpy as np

arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
arr1 = np.zeros((3,3), dtype=int)
arr1

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [3]:
arr2 = np.ones((2,2), dtype=int)
arr2

array([[1, 1],
       [1, 1]])

In [4]:
arr3 = np.arange(1,10,2)
arr3

array([1, 3, 5, 7, 9])

In [5]:
print(np.random.random((10,)))

[0.46711727 0.45483679 0.24009923 0.57195313 0.45341846 0.40073403
 0.40673854 0.25777611 0.81314969 0.72823205]


In [7]:
a=np.arange(4)
b=np.arange(4,8)
print(a+b)

[ 4  6  8 10]


In [8]:
a=np.arange(4)
b=np.arange(4,8)
print(a*b)

[ 0  5 12 21]


In [10]:
A=np.arange(0,9).reshape(3,3)
B=np.ones((3,3))
print(A*B)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


In [11]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
transposed_array = np.transpose(array_2d)

In [13]:
print("Original array:")
print(array_2d)

print("\nTransposed array:")
print(transposed_array)

Original array:
[[1 2 3]
 [4 5 6]]

Transposed array:
[[1 4]
 [2 5]
 [3 6]]


In [14]:
array = np.array([1,5,3,9,7,2,1])
max_value = np.max(array)
print("maximum value:" ,max_value)

maximum value: 9


In [15]:
array = np.array([1,5,3,9,7,2,1])
min_value = np.min(array)
print("minimum value:" ,min_value)

minimum value: 1


In [16]:
array = np.array([1,5,3,9,7,2,1])

mean_value = np.mean(array)
median_value = np.median(array)
std_deviation = np.std(array)

print("Mean:", mean_value)
print("Median:", median_value)
print("Standard Deviation:", std_deviation)

Mean: 4.0
Median: 3.0
Standard Deviation: 2.878491668515698


In [17]:
array_1d = np.array([1,2,3,4,5,6])
array_2d = np.reshape(array_1d, (2, -1))

print("Reshaped 2D array:")
print(array_2d)

Reshaped 2D array:
[[1 2 3]
 [4 5 6]]


In [19]:
array1 = np.array([[1,2],
                    [3,4]])
array2 = np.array([[5,6],
                    [7,8]])
concatenated_array = np.concatenate((array1, array2), axis=1)
print("Concatenated array horizontally:")
print(concatenated_array)

Concatenated array horizontally:
[[1 2 5 6]
 [3 4 7 8]]
