In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

In [2]:
iris = load_iris()
x,y=iris.data,iris.target

In [3]:
print(x.shape)
print(y.shape)

(150, 4)
(150,)


In [5]:
scaler = StandardScaler()
X = scaler.fit_transform(x)

In [6]:
X_train, X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [7]:
knn = KNeighborsClassifier()

In [8]:
param_grid = {
    'n_neighbors' : np.arange(1,10),
    'weights': ['uniform', 'distance'],
}

In [9]:
grid_search = GridSearchCV(knn, param_grid,cv=5)
grid_search.fit(X_train, y_train)

best_k = grid_search.best_params_['n_neighbors']
best_weights = grid_search.best_params_['weights']

print(f"Best K value:{best_k}")
print(f"Best weight function:{best_weights}")

Best K value:4
Best weight function:distance


In [10]:
best_knn = KNeighborsClassifier(n_neighbors=best_k, weights=best_weights)
best_knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=4, weights='distance')

In [11]:
y_pred = best_knn.predict(X_test)

In [12]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))

[[ 4  0  0]
 [ 0  9  2]
 [ 0  2 13]]


In [13]:
accuracy = accuracy_score(y_test,y_pred)
print(f"Test Accuracy:{accuracy:.2f}")

Test Accuracy:0.87
